import type { Metadata } from "next";
import { Orbit } from "next/font/google";
import "./globals.css";

const orbit = Orbit({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-orbit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbit.variable} ${orbit.className} antialiased bg-neutral-900 text-white max-w-screen-sm mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
